version: '3.8'

services:
  wso2-esb:
    image: wso2/wso2esb:6.6.0
    ports:
      - "8280:8280"
      - "8243:8243"
    volumes:
      - ./wso2-esb-config.xml:/home/wso2carbon/wso2esb-6.6.0/repository/deployment/server/synapse-configs/default/proxy-services/BetawareProxy.xml
    environment:
      - CARBON_HOME=/home/wso2carbon/wso2esb-6.6.0
    networks:
      - betaware-network

  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - wso2-esb
    networks:
      - betaware-network

networks:
  betaware-network:
    driver: bridge 