name: Security Pipeline CI

on:
  push:
    branches:
      - main

jobs:
  qodana-sast-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'JetBrains Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2
        with:
          # Esta linha cria um arquivo .zip com o relatório HTML dentro
          artifact-name: qodana-report-html

          # Opcional: Para garantir que o relatório seja gerado mesmo que encontre erros
          # Você pode remover essa linha depois para que o pipeline falhe em caso de erros
          continue-on-error: true
